### ISSUE TITLE
ID如果是普通数字支持不好会报错

### ISSUE THREAD

**Issue by Astralidea** [jike-engineering/Mongo2ES5#22]
ID不只是有用ObjectID的，也有普通数字的情况，普通数字的时候会报错。
对于普通数字，更新支持的也不好。

**Comment by Astralidea** [comment]
oplog TypeError: oplog.o2._id.toHexString is not a function
    at Processor.<anonymous> (/Users/xueyan.li/work/mongo-es/dist/src/processor.js:157:78)
    at Generator.next (<anonymous>)
    at /Users/xueyan.li/work/mongo-es/dist/src/processor.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/xueyan.li/work/mongo-es/dist/src/processor.js:3:12)
    at Processor.oplog (/Users/xueyan.li/work/mongo-es/dist/src/processor.js:140:16)
    at Processor.<anonymous> (/Users/xueyan.li/work/mongo-es/dist/src/processor.js:324:39)
    at Generator.next (<anonymous>)
    at /Users/xueyan.li/work/mongo-es/dist/src/processor.js:7:71
    at new Promise (<anonymous>)

**Comment by Astralidea** [comment]
这个PR不提了，扩展性一点也不好。
