### ISSUE TITLE
tailOpLog Error: should not complete

### ISSUE THREAD

**Issue by flyinghawker** [jike-engineering/Mongo2ES5#27]
I was trying to sync with Alicloud Mongodb service (replicaset), 
when I run the example and got the error as below:

`run 2018-08-17T02:46:30.317Z
put mapping banner_v1 banner
from checkpoint books.books___banner_v1.banner CheckPoint { phase: 'tail', time: 2017-08-16T10:55:24.474Z }
(node:15569) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
tail books.books___banner_v1.banner from 2017-08-16T10:55:24.474Z
tail books.books___banner_v1.banner Error: should not complete
    at AnonymousObserver.tail.bufferWithTimeOrCount.subscribe [as _onCompleted] (/home/michael/another-connector/node_modules/mongo-es/dist/src/processor.js:302:33)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/home/michael/another-connector/node_modules/rx/dist/rx.js:1843:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/michael/another-connector/node_modules/rx/dist/rx.js:1782:14)
    at AnonymousObserver.tryCatcher (/home/michael/another-connector/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.completed (/home/michael/another-connector/node_modules/rx/dist/rx.js:5897:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/michael/another-connector/node_modules/rx/dist/rx.js:1782:14)
    at MergeAllObserver.completed (/home/michael/another-connector/node_modules/rx/dist/rx.js:3751:37)
    at MergeAllObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/michael/another-connector/node_modules/rx/dist/rx.js:1782:14)
    at MergeAllObserver.tryCatcher (/home/michael/another-connector/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.completed (/home/michael/another-connector/node_modules/rx/dist/rx.js:5897:56)
tailOpLog Error: should not complete
    at AnonymousObserver.tail.bufferWithTimeOrCount.subscribe [as _onCompleted] (/home/michael/another-connector/node_modules/mongo-es/dist/src/processor.js:302:33)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/home/michael/another-connector/node_modules/rx/dist/rx.js:1843:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/michael/another-connector/node_modules/rx/dist/rx.js:1782:14)
    at AnonymousObserver.tryCatcher (/home/michael/another-connector/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.completed (/home/michael/another-connector/node_modules/rx/dist/rx.js:5897:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/michael/another-connector/node_modules/rx/dist/rx.js:1782:14)
    at MergeAllObserver.completed (/home/michael/another-connector/node_modules/rx/dist/rx.js:3751:37)
    at MergeAllObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/home/michael/another-connector/node_modules/rx/dist/rx.js:1782:14)
    at MergeAllObserver.tryCatcher (/home/michael/another-connector/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.completed (/home/michael/another-connector/node_modules/rx/dist/rx.js:5897:56)`

here is config.json

**{
  "controls": {
    "mongodbReadCapacity": 10000,
    "elasticsearchBulkSize": 5000,
    "elasticsearchBulkInterval": 5000,
    "indexNameSuffix": "_v1"
  },
  "mongodb": {
    "url": "mongodb://michael:xxxxx@dds-xxxxx.mongodb.rds.aliyuncs.com:3717,dds-xxxxxx.mongodb.rds.aliyuncs.com:3717/books?replicaSet=mgset-xxxxx",
    "options": {
      "authSource": "admin",
      "readPreference": "secondaryPreferred"
    }
  },
  "elasticsearch": {
    "options": {
      "host": "http://localhost:9200",
      "apiVersion": "6.3"
    },
    "indices": [
      {
        "index": "banner",
        "body": {
          "settings": {
            "index": {
              "number_of_shards": 3,
              "number_of_replicas": 1,
              "mapper.dynamic": false
            }
          }
        }
      }
    ]
  },
 "tasks": [
    {
      "from": {
        "phase": "tail",
        "time": "2017-08-16T10:55:24.474Z"
      },
      "extract": {
        "db": "books",
        "collection": "books",
        "projection": {
          "name": 1
        }
      },
      "transform": {
        "mapping": {
          "name": "name"
        }
      },
      "load": {
        "index": "banner",
        "type": "banner",
        "body": {
          "dynamic": false,
          "properties": {
            "name": {
              "type": "text",
              "fields": {
                "exact": {
                  "type": "keyword"
                }
              }
            }
          }
        }
      }
    }
  ]
}**

**Comment by flyinghawker** [comment]
I read the source code and guess the oplog tail operation has issue but not sure how to dig into it.

> async tailOpLog(): Promise<never> {
    return new Promise<never>((resolve, reject) => {
      this.tail()
        .bufferWithTimeOrCount(
          this.controls.elasticsearchBulkInterval,
          this.controls.elasticsearchBulkSize,
        )
        .subscribe(
          oplogs => {
            this.queue.push(oplogs)
            if (!this.running) {
              this.running = true
              setImmediate(this._processOplog.bind(this))
            }
          },
          err => {
            console.error('tail', this.task.name(), err)
            reject(err)
          },
          () => {
            const err = new Error('should not complete')
            console.error('tail', this.task.name(), err)
            reject(err)
          },
        )
    })
  }

**Comment by flyinghawker** [comment]
as instructed, 
**notice: must use a admin user to access oplog.**
not sure what does that mean and how to implement.
I create the user "michael" from admin db and assign right "readWrite" to database "books"

**Comment by aliez-ren** [comment]
@flyinghawker 
- mongod should running with `--replSet`
- user should have read permission of `local.oplog.rs`
