### ISSUE TITLE
报错信息看不懂

### ISSUE THREAD

**Issue by thedogb** [jike-engineering/Mongo2ES5#28]
···
run 2018-11-16T15:38:59.190Z
put mapping douban_v1 movie
from checkpoint douban.movie___douban_v1.movie CheckPoint {
  phase: 'scan',
  id: 000000000000000000000000,
  time: 2018-11-16T15:38:59.189Z }
scan douban.movie___douban_v1.movie from 000000000000000000000000
scan douban.movie___douban_v1.movie end
tail douban.movie___douban_v1.movie from 2018-11-16T15:38:59.189Z
tail douban.movie___douban_v1.movie Error: should not complete
    at AnonymousObserver.tail.bufferWithTimeOrCount.subscribe [as _onCompleted] (/usr/local/lib/node_modules/mongo-es/dist/src/processor.js:302:33)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/mongo-es/node_modules/rx/dist/rx.js:1843:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/mongo-es/node_modules/rx/dist/rx.js:1782:14)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/mongo-es/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/mongo-es/node_modules/rx/dist/rx.js:5897:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/mongo-es/node_modules/rx/dist/rx.js:1782:14)
    at MergeAllObserver.completed (/usr/local/lib/node_modules/mongo-es/node_modules/rx/dist/rx.js:3751:37)
    at MergeAllObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/mongo-es/node_modules/rx/dist/rx.js:1782:14)
    at MergeAllObserver.tryCatcher (/usr/local/lib/node_modules/mongo-es/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/mongo-es/node_modules/rx/dist/rx.js:5897:56)
tailOpLog Error: should not complete
    at AnonymousObserver.tail.bufferWithTimeOrCount.subscribe [as _onCompleted] (/usr/local/lib/node_modules/mongo-es/dist/src/processor.js:302:33)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/mongo-es/node_modules/rx/dist/rx.js:1843:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/mongo-es/node_modules/rx/dist/rx.js:1782:14)
    at AnonymousObserver.tryCatcher (/usr/local/lib/node_modules/mongo-es/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/mongo-es/node_modules/rx/dist/rx.js:5897:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/mongo-es/node_modules/rx/dist/rx.js:1782:14)
    at MergeAllObserver.completed (/usr/local/lib/node_modules/mongo-es/node_modules/rx/dist/rx.js:3751:37)
    at MergeAllObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/mongo-es/node_modules/rx/dist/rx.js:1782:14)
    at MergeAllObserver.tryCatcher (/usr/local/lib/node_modules/mongo-es/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/mongo-es/node_modules/rx/dist/rx.js:5897:56)
···
这是我的报错日志，经过搜索之后发现，似乎是我的mongo没有开oplog导致的。我并不会js，单看这段报错日志完全不知道是这个原因，希望能提供更好的报错信息来方便进行调试与排错。

**Comment by fairytail111** [comment]
你好，我看到你的运行中有scan阶段，你是怎么配置的，为什么我的没有scan阶段

**Comment by thedogb** [comment]
@fairytail111 抱歉，相关代码我已经删除了，所以，我也不太清楚了。

**Comment by fairytail111** [comment]
哦哦，这样啊，谢谢你！
