### ISSUE TITLE
win10下出现这个错误 是怎么回事呢

### ISSUE THREAD

**Issue by tangniyuqi** [jike-engineering/Mongo2ES5#3]
D:\mongo-es>mongo-es config.json
run 2017-06-20T02:43:49.685Z
run { Error: [mapper_parsing_exception] analyzer [ik_max_word] not found for field [property0]
    at respond (C:\Users\tangniyuqi\AppData\Roaming\npm\node_modules\mongo-es\node_modules\elasticsearch\src\lib\transport.js:295:15)
    at checkRespForFailure (C:\Users\tangniyuqi\AppData\Roaming\npm\node_modules\mongo-es\node_modules\elasticsearch\src\lib\transport.js:254:7)
    at HttpConnector.<anonymous> (C:\Users\tangniyuqi\AppData\Roaming\npm\node_modules\mongo-es\node_modules\elasticsearch\src\lib\connectors\http.js:159:7)
    at IncomingMessage.bound (C:\Users\tangniyuqi\AppData\Roaming\npm\node_modules\mongo-es\node_modules\elasticsearch\node_modules\lodash\dist\lodash.js:729:21)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  status: 400,
  displayName: 'BadRequest',
  message: '[mapper_parsing_exception] analyzer [ik_max_word] not found for field [property0]',
  path: '/index0_v1/_mapping/type0',
  query: {},
  body: '{"dynamic":false,"_parent":{"type":"type1"},"properties":{"property0":{"type":"text","norms":false,"analyzer":"ik_max_word","search_analyzer":"ik_smart"},"property1":{"type":"keyword"}}}',
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"analyzer [ik_max_word] not found for field [property0]"}],"type":"mapper_parsing_exception","reason":"analyzer [ik_max_word] not found for field [property0]"},"status":400}',
  toString: [Function],
  toJSON: [Function] }

**Comment by aliez-ren** [comment]
es安装的不对，没有ik_max_word这个analyzer

**Comment by tangniyuqi** [comment]
@RenzHoly thanks
